/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 7skiessolutions
 */
public class ManageBooks extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
  
    DefaultTableModel model;
    public ManageBooks() {
        initComponents();
        setBookDetailsToDatabase();
    }
    // to set the book details into the table
public void setBookDetailsToDatabase(){
    try {
         Connection con =DBConnection.getConnection();
        Statement st=con.createStatement();
       ResultSet rs= st.executeQuery("select *  from book_details");
       while(rs.next()){
           String bookId=rs.getString("book_id");
           String bookName=rs.getString("bookname");
           String bookAuthor=rs.getString("author");
           int bookQuantity=rs.getInt("quantity");
           Object[] obj={bookId,bookName,bookAuthor,bookQuantity};
           model=(DefaultTableModel)tbl_bookDetalis.getModel();
           model.addRow(obj);
           
       }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    

//to add book details to table

public boolean addBook(){
boolean isAdded=false;
    int bookId=Integer.parseInt(book_id.getText());
    String bookName=book_name.getText();
    String author=author_name.getText();
    int bookquantity=Integer.parseInt(quantity.getText());
    
    try {
        Connection con=DBConnection.getConnection();
        String sql="insert into book_details  values(?,?,?,?)";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setInt(1, bookId);
        pst.setString(2, bookName);
        pst.setString(3, author);
        pst.setInt(4, bookquantity);
        
        int rowCount=pst.executeUpdate();
        if(rowCount>0){
            isAdded=true;
        }else{
        isAdded=false;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    return isAdded;
}
//to Update book details to table

public boolean updateBook(){
boolean isUpdate=false;
    int bookId=Integer.parseInt(book_id.getText());
    String bookName=book_name.getText();
    String author=author_name.getText();
    int bookquantity=Integer.parseInt(quantity.getText());
    
    try {
        Connection con=DBConnection.getConnection();
        String sql="update book_details  set bookname = ?,author = ?,quantity = ? where book_id=?";
        PreparedStatement pst=con.prepareStatement(sql);
        
     
        pst.setString(1, bookName);
        pst.setString(2, author);
        pst.setInt(3, bookquantity);
           pst.setInt(4, bookId);
        
        int rowCount=pst.executeUpdate();
        if(rowCount>0){
            isUpdate=true;
        }else{
        isUpdate=false;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    return isUpdate;
}
//to Delete book details to table

public boolean deleteBook(){
boolean isDelete=false;
    int bookId=Integer.parseInt(book_id.getText());

    
    try {
        Connection con=DBConnection.getConnection();
        String sql="delete from book_details  where book_id = ? ";
        PreparedStatement pst=con.prepareStatement(sql);
        
     
       
           pst.setInt(1, bookId);
        
        int rowCount=pst.executeUpdate();
        if(rowCount>0){
            isDelete=true;
        }else{
        isDelete=false;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    return isDelete;
}
//clear table
public void clearTable(){
DefaultTableModel model=(DefaultTableModel)tbl_bookDetalis.getModel();
model.setRowCount(0);
}
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_id = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        book_name = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        author_name = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quantity = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bookDetalis = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        book_id.setBackground(new java.awt.Color(0, 51, 204));
        book_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        book_id.setForeground(new java.awt.Color(255, 255, 255));
        book_id.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        book_id.setPhColor(new java.awt.Color(255, 255, 255));
        book_id.setPlaceholder("Enter Book Id");
        book_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                book_idFocusLost(evt);
            }
        });
        jPanel1.add(book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 230, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 50));

        book_name.setBackground(new java.awt.Color(0, 51, 204));
        book_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        book_name.setForeground(new java.awt.Color(255, 255, 255));
        book_name.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        book_name.setPhColor(new java.awt.Color(255, 255, 255));
        book_name.setPlaceholder("Enter Book Name");
        book_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                book_nameFocusLost(evt);
            }
        });
        jPanel1.add(book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 230, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter Book Nmae");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 200, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 50));

        author_name.setBackground(new java.awt.Color(0, 51, 204));
        author_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        author_name.setForeground(new java.awt.Color(255, 255, 255));
        author_name.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        author_name.setPhColor(new java.awt.Color(255, 255, 255));
        author_name.setPlaceholder("Enter Author Name");
        author_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                author_nameFocusLost(evt);
            }
        });
        jPanel1.add(author_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 230, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Author Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, 50));

        quantity.setBackground(new java.awt.Color(0, 51, 204));
        quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        quantity.setForeground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        quantity.setPhColor(new java.awt.Color(255, 255, 255));
        quantity.setPlaceholder("Enter Quantity");
        quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFocusLost(evt);
            }
        });
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 230, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 200, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 50, 50));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonRectangle1.setText("Delete");
        rSMaterialButtonRectangle1.setActionCommand("Delete");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 120, 60));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(51, 102, 255));
        rSMaterialButtonRectangle2.setText("add");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 120, 60));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(0, 153, 0));
        rSMaterialButtonRectangle3.setText("update");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 120, 60));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enter Book Id");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 830));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 60, 40));

        tbl_bookDetalis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Name", "Author", "Quantity"
            }
        ));
        tbl_bookDetalis.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_bookDetalis.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_bookDetalis.setColorBordeHead(new java.awt.Color(51, 51, 51));
        tbl_bookDetalis.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_bookDetalis.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_bookDetalis.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        tbl_bookDetalis.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_bookDetalis.setFuenteFilasSelect(new java.awt.Font("Yu Gothic Light", 1, 20)); // NOI18N
        tbl_bookDetalis.setFuenteHead(new java.awt.Font("Yu Gothic Light", 1, 20)); // NOI18N
        tbl_bookDetalis.setRowHeight(30);
        tbl_bookDetalis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookDetalisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_bookDetalis);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 730, 280));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel2.setText("Manage Books");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 300, 5));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 780, 830));

        setSize(new java.awt.Dimension(1200, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void book_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_idFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_book_idFocusLost

    private void book_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_book_nameFocusLost

    private void author_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_author_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_author_nameFocusLost

    private void quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFocusLost

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
          if(deleteBook()==true){
           JOptionPane.showMessageDialog(this, "Book Deleted");
           clearTable();
           setBookDetailsToDatabase();
       }else{
            JOptionPane.showMessageDialog(this, "Book Deletion Failed");
    }  // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
       if(addBook()==true){
           JOptionPane.showMessageDialog(this, "Book Added");
           clearTable();
           setBookDetailsToDatabase();
       }else{
            JOptionPane.showMessageDialog(this, "Book Addition Failed");
    }
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
         if(updateBook()==true){
           JOptionPane.showMessageDialog(this, "Book Updated");
           clearTable();
           setBookDetailsToDatabase();
       }else{
            JOptionPane.showMessageDialog(this, "Book Updation Failed");
    }
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
      System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void tbl_bookDetalisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookDetalisMouseClicked
    int rowno=tbl_bookDetalis.getSelectedRow();
        TableModel model=tbl_bookDetalis.getModel();
        
       book_id.setText(model.getValueAt(rowno, 0).toString());
       book_name.setText(model.getValueAt(rowno, 1).toString());
       author_name.setText(model.getValueAt(rowno, 2).toString());
       quantity.setText(model.getValueAt(rowno, 3).toString());
    }//GEN-LAST:event_tbl_bookDetalisMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage page=new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField author_name;
    private app.bolivia.swing.JCTextField book_id;
    private app.bolivia.swing.JCTextField book_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private app.bolivia.swing.JCTextField quantity;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSTableMetro tbl_bookDetalis;
    // End of variables declaration//GEN-END:variables
}
